auth_enabled: false # выключаем авторизацию для локальной среды

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1 # один инстанс без репликаций
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01 # дата начала схемы
      store: tsdb # тип хранилища индекса
      object_store: filesystem # объектное хранилище файловая система
      schema: v13 # версия схемы
      index:
        prefix: index_ # префикс имени индекса
        period: 24h # период индекса
